### ISSUE TITLE
'./config.js' issue on windows

### ISSUE THREAD

**Issue by rkdaredevil** [MarcusHurney/Point-Of-Sale-System#2]
> node server.js

module.js:471
    throw err;
    ^

Error: Cannot find module './config.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Vivek Singh\Desktop\Point-Of-Sale-System\settings\config.js:4:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! server@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the server@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Vivek Singh\AppData\Roaming\npm-cache\_logs\2017-08-08T16_31_43_124Z-debug.log

**Comment by MarcusHurney** [comment]
config.js should contain the API keys and database information that you need to run your own instance of the POS system. I didn't include this in the repository because it is private information for each user.

**Comment by rkdaredevil** [comment]
As I'm also a mean stack developer can you please mail me config.js
structure.
Regards

**Comment by stasKaufman** [comment]
Hi,
Is it possible to publish an example (structure) of config.json file that you require ?

**Comment by jaxtisapia** [comment]
I worked around it, just sharing with you guys
{
     "development":{
            "JWT_SECRET":"ANY_STRING_IS_OKAY",
            "PORT":9000,
            "MONGODB_URI":"mongodb://name:password@ds135534.mlab.com:35534/my_database"
     }
}
